# Generated by Django 4.1.3 on 2022-11-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requirement_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.requirement'),
            preserve_default=False,
        ),
    ]
