# Generated by Django 4.1.3 on 2022-11-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='taskMember', to='core.member'),
        ),
    ]
